import { defineConfig } from 'eslint/config';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';

// Generated by: pnpm dlx @eslint/migrate-config .eslintrc.json
// https://eslint.org/docs/latest/use/configure/migration-guide

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all
});

export default defineConfig([
  {
    extends: compat.extends('./node_modules/gts/'),

    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/prefer-type-literal': 'off',

      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_'
        }
      ],

      '@typescript-eslint/ban-ts-comment': 'off',
      'n/no-process-exit': 'off',
      'n/no-unpublished-require': 'off',
      'n/no-unsupported-features/node-builtins': 'off',
      'n/no-unsupported-features/es-syntax': 'off',
      'no-case-declarations': 'off',
      'no-useless-escape': 'off',

      'no-constant-condition': [
        'error',
        {
          checkLoops: false
        }
      ]
    }
  },
  // https://eslint.org/docs/latest/use/configure/migration-guide#ignore-files
  {
    // Note: there should be no other properties in this object
    /*
    build
scripts
dist
node_modules
cdk.out

    */
    ignores: ['build', 'scripts', 'dist', 'node_modules', 'cdk.out']
  }
]);
