import { defineConfig, globalIgnores } from 'eslint/config';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import { FlatCompat } from '@eslint/eslintrc';

import * as gts from 'gts';

// Generated by: pnpm dlx @eslint/migrate-config .eslintrc.json
// https://eslint.org/docs/latest/use/configure/migration-guide

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all
});

// const pkgs = 'app capacity-manager cli db example-worker infra types web-api'.split(' ');
// ignore these directories within packages
// packages/*/X/**
const pkg_ignored_dirs = [
  'build',
  'scripts',
  'dist',
  'node_modules',
  '.turbo',
  'cdk.out',
  '.angular'
].map(x => `packages/*/${x}/**`);

export default defineConfig(
  // this style is from https://typescript-eslint.io/getting-started
  js.configs.recommended,
  tseslint.configs.recommended,
  {
    // FIXME get this working again
    // extends: compat.extends(gts.default),

    rules: {
      // TODO remove and fix error cause later
      'preserve-caught-error': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/prefer-type-literal': 'off',

      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_'
        }
      ],

      '@typescript-eslint/ban-ts-comment': 'off',
      'n/no-process-exit': 'off',
      'n/no-unpublished-require': 'off',
      'n/no-unsupported-features/node-builtins': 'off',
      'n/no-unsupported-features/es-syntax': 'off',
      'no-case-declarations': 'off',
      'no-useless-escape': 'off',

      'no-constant-condition': [
        'error',
        {
          checkLoops: false
        }
      ]
    }
  },
  [
    globalIgnores([
      '.github/**',
      '.idea/**',
      '.turbo/**',
      '.vscode/**',
      'node_modules/**',
      ...pkg_ignored_dirs
    ])
  ]
);
