packages:
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - unrs-resolver

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@angular/*'
  - '@angular-devkit/*'
  - '@ngtools/webpack'
  - '@schematics/angular'

trustPolicy: no-downgrade
